<a href="https://colab.research.google.com/drive/1m7qBSGQMrAihATvdW-Has-BmqKjDHlLd#scrollTo=KTL7PREhsDdL"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>

# Pandas
---

- Nombre: Jhon Edwar Suarez Quiñonez

- Universidad: Universidad Del Pacifico

- Programa: Ingenieria en Sistemas

- Asignatura: Inteligencia Artificial

- Buenaventura, Valle del Cauca - Colombia

- Año: 2026

## ¿Que es pandas?

Es una libreria de codigo abierto para programar en Python.
Proporciona estructuras de datos y herramientas para analizar datos de alto rendimiento y son muy faciles de usar. Su nombre proviene de la expresion "Panel Data".

## ¿Para que sirve?

Principamente para la manipulacion, exploracion, limpieza y analisis de datos. Permita trabaja con datos estructurados (tablas, hojas de cálculo, bases de datos SQL, archivos CSV, etc.) de forma intuitiva, lo que facilita operaciones como filtrado, agrupación, combinación, manejo de valores nulos y transformación de datos en general.

## Objetivo principal de la librería

El objetivo principal de Pandas es proporcionar los bloques de construcción fundamentales de alto nivel necesarios para hacer el análisis práctico de datos reales en Python rápido y fácil. Busca ser la herramienta más potente y flexible para la manipulación de datos open-source disponible en cualquier lenguaje.

## Principales funciones y características

-   **Estructuras de datos:** Introduce los DataFrame (estructuras 2D tabulares) y las Series (arrays 1D indexados).

-   **Manejo de datos faltantes:** Herramientas eficientes para detectar, eliminar o rellenar valores nulos (NaN).

-   **Operaciones vectorizadas:** Al estar construida sobre NumPy, las operaciones numéricas sobre las columnas son extremadamente rápidas sin necesidad de usar bucles **for** explícitos.

-   **Alineación inteligente de datos:** Evita errores comunes al asegurar que los datos estén alineados según sus etiquetas (índices) durante los cálculos.

-   **Agrupación y agregación:** Funcionalidad poderosa ***groupby*** para dividir, aplicar y combinar conjuntos de datos.

-   **Lectura/Escritura versátil:** Soporta una amplia variedad de formatos (CSV, Excel, SQL, JSON, etc.).

-   **Fusión (Merge/Join):** Herramientas fáciles de usar para cruzar y unir múltiples conjuntos de dato.



## Importancia de Pandas en la Inteligencia Artificial y el análisis de datos

En la IA y el Aprendizaje Automático (Machine Learning), la calidad de los modelos depende directamente de la calidad de los datos. Antes de entrenar cualquier algoritmo predictivo, los datos deben ser limpiados, procesados y estructurados correctamente. Pandas es el estándar de la industria en Python para realizar esta fase de preprocesamiento (conocida como *Data Wrangling* o *Feature Engineering*), convirtiéndose en un paso previo casi obligatorio antes de alimentar los datos a librerías de IA como Scikit-Learn, TensorFlow o PyTorch.

#Ejercicios con Pandas.

## 1. Importar libreria
Primero importamos las librerias necesarias para trabaja, en este caso **Pandas Y Numpy** .

In [ ]:
import pandas as pd
import numpy as np

## 2. Creamos un DataFrame.

Un DataFrame es una estructura de datos bidimensional y tabular(compuestas por filas y columnas), similar a una hoja de calculo en Excel o una tabla en SQL.

En este caso, crearemos un DataFrame a partir de un diccionario, que tendra las nostas de 5 estudiantes en tres cortes, las notas seran evaludas de 0-100

In [11]:
datos_alumnos = {
    "Estudiante": ["Miguel", "Sofía", "Javier", "Laura", "Andrés"],
    "Corte 1": [90, 64, 56, 100, 70],
    "Corte 2": [80, 76, 60, 96, 84],
    "Corte 3": [76, 80, 70, 90, 80]
}


df_notas = pd.DataFrame(datos_alumnos)

#Para visualizar el DataFrame
print("Registro de Notas inicial:")
display(df_notas)

Registro de Notas inicial:

  Estudiante  Corte 1  Corte 2  Corte 3
0     Miguel       90       80       76
1      Sofía       64       76       80
2     Javier       56       60       70
3      Laura      100       96       90
4     Andrés       70       84       80

## 3. Operaciones entre columnas.

Tomaremos las notas definivas de cada corte para saber el promedio de cada estudiante.

In [12]:
df_notas["Promedio Actual"] = ((df_notas["Corte 1"] + df_notas["Corte 2"] + df_notas["Corte 3"]) / 3).round(1)

print("\nDataFrame con el cálculo del promedio:")
display(df_notas)

DataFrame con el cálculo del promedio:

  Estudiante  Corte 1  Corte 2  Corte 3  Promedio Actual
0     Miguel       90       80       76             82.0
1      Sofía       64       76       80             73.3
2     Javier       56       60       70             62.0
3      Laura      100       96       90             95.3
4     Andrés       70       84       80             78.0

## 4. Leer archivos CSV

In [15]:
import io

try:
    # Librería exclusiva de Google Colab para interactuar con archivos
    from google.colab import files

    print("Por favor, presiona 'Elegir archivos' y sube tu CSV de notas:\n")
    archivo_subido = files.upload()

    # Extraemos el nombre del archivo que acabas de subir
    nombre_archivo = list(archivo_subido.keys())[0]

    # Usamos Pandas para leer el archivo directamente desde la memoria
    df_cargado = pd.read_csv(io.BytesIO(archivo_subido[nombre_archivo]))

    print(f"\n¡Excelente! Se han cargado correctamente los datos desde: {nombre_archivo}")
    display(df_cargado)

except ImportError:
    print("Este código utiliza el selector interactivo de Google Colab.")

Por favor, presiona 'Elegir archivos' y sube tu CSV de notas:

Saving notas_estudiantes.csv to notas_estudiantes (1).csv

¡Excelente! Se han cargado correctamente los datos desde: notas_estudiantes (1).csv

  Estudiante  Corte 1  Corte 2  Corte 3
0     Miguel       90       80       76
1      Sofía       64       76       80
2     Javier       56       60       70
3      Laura      100       96       90
4     Andrés       70       84       80

## 5. Datos sinteticos.

Son informacion generada artificialmente mediante algoritmos y modelos de inteligencia artificial que la imitan las caracteristicas estadisticas, relaciones y estructuras de datos reales.

In [18]:
np.random.seed(123) # Para reproducibilidad

# Generamos notas aleatorias para 10 alumnos en cada uno de los 3 cortes
datos_sinteticos = {
    "ID_Alumno": range(1001, 1011),
    "Corte 1": np.random.randint(30, 101, 10),
    "Corte 2": np.random.randint(30, 101, 10),
    "Corte 3": np.random.randint(30, 101, 10)
}

df_sintetico = pd.DataFrame(datos_sinteticos)

# Reutilizamos la lógica del paso 3 para sacar su promedio final
df_sintetico["Promedio Final"] = ((df_sintetico["Corte 1"] +
                                   df_sintetico["Corte 2"] +
                                   df_sintetico["Corte 3"]) / 3).round(1)

print("\nDatos sintéticos generados:")
display(df_sintetico)

Datos sintéticos generados:

   ID_Alumno  Corte 1  Corte 2  Corte 3  Promedio Final
0       1001       96       85       57            79.3
1       1002       47       97       64            69.3
2       1003       87       32       70            63.0
3       1004       77       69       33            59.7
4       1005       62       96       99            85.7
5       1006       76       77       94            82.3
6       1007       55       91       64            70.0
7       1008       66       78       88            77.3
8       1009       98       37       40            58.3
9       1010       79       82       52            71.0

## 6. Estadisticas basicas.

Con Pandas es facil obtener un resumen estadistico descriptivo (media, maximos, minimos, desviaciones).

In [19]:
#El metodo .describe() nos dara la estadistica de cada corte y del promedio final
print("\nEstadísticas descriptivas generales de la clase sintética:")
display(df_sintetico.describe())

Estadísticas descriptivas generales de la clase sintética:

        ID_Alumno    Corte 1   Corte 2    Corte 3  Promedio Final
count    10.00000  10.000000  10.00000  10.000000       10.000000
mean   1005.50000  74.300000  74.40000  66.100000       71.590000
std       3.02765  16.878981  22.77523  22.168296        9.461906
min    1001.00000  47.000000  32.00000  33.000000       58.300000
25%    1003.25000  63.000000  71.00000  53.250000       64.575000
50%    1005.50000  76.500000  80.00000  64.000000       70.500000
75%    1007.75000  85.000000  89.50000  83.500000       78.800000
max    1010.00000  98.000000  97.00000  99.000000       85.700000

## 7. Filtrar datos

In [20]:
aprobados = df_sintetico[df_sintetico["Promedio Final"] >= 60]

print(f"\nDe los 10 estudiantes simulados, se encontraron {len(aprobados)} estudiantes aprobados.")
print("Muestra de los aprobados:")
display(aprobados)

De los 10 estudiantes simulados, se encontraron 8 estudiantes aprobados.
Muestra de los aprobados:

   ID_Alumno  Corte 1  Corte 2  Corte 3  Promedio Final
0       1001       96       85       57            79.3
1       1002       47       97       64            69.3
2       1003       87       32       70            63.0
4       1005       62       96       99            85.7
5       1006       76       77       94            82.3
6       1007       55       91       64            70.0
7       1008       66       78       88            77.3
9       1010       79       82       52            71.0